/* Screening coverage figures — generated from the engine's own configuration,
   never hand-counted.

   The README coverage badges (adverse-media editions, countries and languages;
   sanctions lists and jurisdictions) read data/coverage-figures.json. The
   numbers come from the same structures the screen runs on:
     - scripts/adverse-media.mjs  LOCALES (Google News editions) and LANG_TERMS
       (the languages the risk-term scorer reads);
     - data/sanctions-sources.json + data/sanctions-extra.json, filtered by the
       exact rule sanctions-screen.mjs loadAllLists uses (enabled !== false, and
       for extra sources a url or file), minus alias-only sources (mergeInto),
       which fold into their primary list rather than screening as one.
   So a badge can only move when the screen's configuration moves, and
   `--check` (a CI drift step) fails whenever the committed file lags it.

   These are CONFIGURED coverage figures, not per-run results: a list that
   fails to load on a given run is reported by that run (degraded), not here.

   Usage:
     node scripts/coverage-figures.mjs           # print the computed figures
     node scripts/coverage-figures.mjs --write   # refresh data/coverage-figures.json
     node scripts/coverage-figures.mjs --check   # exit 1 if the committed file drifted */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join, resolve } from 'node:path';
import { LOCALES, LANG_TERMS } from './adverse-media.mjs';

export const FIGURES_FILE = 'data/coverage-figures.json';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/* The sources the screen actually loads, as sanctions-screen.mjs selects them. */
export function screenedSources(root = ROOT) {
  const read = (f) => (JSON.parse(readFileSync(join(root, f), 'utf8')).sources || []);
  const core = read('data/sanctions-sources.json').filter(s => s && s.enabled !== false);
  const extra = read('data/sanctions-extra.json').filter(s => s && s.enabled !== false && (s.url || s.file));
  return [...core, ...extra].filter(s => !s.mergeInto);
}

export function buildFigures(root = ROOT) {
  const sources = screenedSources(root);
  const jurisdictions = new Set(sources
    .map(s => String(s.jurisdiction || '').trim())
    .filter(j => j && !/^global\b/i.test(j)));
  return {
    adverseMediaEditions: LOCALES.length,
    adverseMediaCountries: new Set(LOCALES.map(l => l.gl)).size,
    adverseMediaLanguages: Object.keys(LANG_TERMS).length,
    sanctionsLists: sources.length,
    sanctionsJurisdictions: jurisdictions.size,
  };
}

export function buildFile(root = ROOT) {
  return {
    _README: 'Configured screening coverage, generated by scripts/coverage-figures.mjs from the engine\'s own configuration. Never hand-edit: run `node scripts/coverage-figures.mjs --write` to refresh. CI fails when the committed figures drift from the configuration. These are configured figures; a source that fails on a given run is reported by that run as degraded.',
    figures: buildFigures(root),
    definitions: {
      adverseMediaEditions: 'Google News country/language editions in the adverse-media locale matrix (scripts/adverse-media.mjs LOCALES); the daily run sweeps a budgeted rotation of them plus GDELT and Bing News',
      adverseMediaCountries: 'distinct countries (gl) across those editions',
      adverseMediaLanguages: 'languages with native risk terms in the scorer (scripts/adverse-media.mjs LANG_TERMS)',
      sanctionsLists: 'enabled sources in data/sanctions-sources.json + data/sanctions-extra.json (extra: with url or file), excluding alias-only sources (mergeInto)',
      sanctionsJurisdictions: 'distinct national jurisdictions among those sources (entries marked Global — UN, EU, OFAC, OFSI, MDB lists — excluded)',
    },
  };
}

function main() {
  const mode = process.argv[2] || '';
  const fresh = buildFile();
  if (mode === '--write') {
    writeFileSync(join(ROOT, FIGURES_FILE), JSON.stringify(fresh, null, 2) + '\n');
    console.log('wrote ' + FIGURES_FILE + ': ' + JSON.stringify(fresh.figures));
    return;
  }
  console.log(JSON.stringify(fresh.figures, null, 2));
  if (mode === '--check') {
    let committed = null;
    try { committed = JSON.parse(readFileSync(join(ROOT, FIGURES_FILE), 'utf8')); } catch { /* reported below */ }
    if (!committed || JSON.stringify(committed.figures) !== JSON.stringify(fresh.figures)) {
      console.error('DRIFT: committed ' + JSON.stringify(committed && committed.figures)
        + ' vs live ' + JSON.stringify(fresh.figures)
        + ' — run `node scripts/coverage-figures.mjs --write` and commit.');
      process.exitCode = 1;
    } else {
      console.log('coverage-figures: ' + FIGURES_FILE + ' is in sync.');
    }
  }
}

if (import.meta.url === pathToFileURL(process.argv[1] || '').href) {
  main();
}
